
services:
  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    networks:
      - app-network

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    networks:
      - app-network

  customer-service:
    build:
      context: .
      dockerfile: customer-service/Dockerfile
    ports:
      - "8085:8085"
    volumes:
      - .:/app
    networks:
      - app-network

  purchase-service:
    build:
      context: .
      dockerfile: purchase-service/Dockerfile
    ports:
      - "8086:8086"
    volumes:
      - .:/app
    environment:
      PRODUCT_SERVICE_URL: http://product-service:8081
      INVENTORY_SERVICE_URL: http://inventory-service:8082
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate --url http://frontend:5173
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
